name: build-and-run

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            meson
            ninja

      # Build libstar with Meson
      - name: meson build
        run: |
          cd libstar
          meson setup build
          meson compile -C build

      # Run examples
      - name: run console example
        run: |
          ./libstar/build/libstar-console-example

  build-daisy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ARM build toolchain
        run: brew install gcc-arm-embedded

      - name: Build libDaisy dependency
        run: |
          cd hosts/daisy/vendor/libDaisy
          make
      - name: Build app
        run: |
          cd hosts/daisy/examples/bluemchen
          make
