name: build-and-run

on: [push, pull_request]

jobs:
  build-libstar:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            meson
            ninja
      - uses: mymindstorm/setup-emsdk@v11

      - name: Prepare MSVC (Windows-only)
        if: runner.os == 'Windows'
        uses: bus1/cabuild/action/msdevshell@v1

      # Build libstar for the native architecture
      - name: Native build
        run: |
          cd libstar
          meson setup build/native
          meson compile -C build/native

      # Build libstar for wasm
      # TODO: Windows can't run generate-wasm-bindings.sh;
      # need to add cross-platform support for it.
      # This will be fixed by gh-18 (Docker support)
      - name: Web Assembly build
        if: runner.os != 'Windows'
        run: |
          git clone https://github.com/emscripten-core/emscripten.git
          export EMSCRIPTEN_TOOLS_PATH=$PWD/emscripten/tools
          cd libstar
          meson setup build/wasm --cross-file wasm-cross-compile.txt
          ./generate-wasm-bindings.sh
          meson compile -C build/wasm

      # Tests
      - name: Run native unit tests
        run: |
          cd libstar
          meson test -C build/native -v

      - name: Run unit tests in Node.js
        if: runner.os != 'Windows'
        run: |
          cd libstar
          meson test -C build/wasm -v

      # Run examples
      - name: run console example
        run: ./libstar/build/native/libstar-console-example

      - name: run console example in Node.js
        if: runner.os != 'Windows'
        run: node ./libstar/build/wasm/libstar-console-example.js

  build-daisy-host:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ARM toolchain
        # We only install ARM GCC, since we don't need the other
        # tools in the Daisy Toolchain and they're slow to install.
        run: |
          git clone https://github.com/electro-smith/DaisyToolchain.git
          cd DaisyToolchain/macOS
          brew install ./gcc-arm-embedded.rb --cask

      - name: Build libDaisy dependency
        run: |
          cd hosts/daisy/vendor/libDaisy
          make
      - name: Build Bluemchen example
        run: |
          cd hosts/daisy/examples/bluemchen
          make
